/**
 * SVG export functionality for patterns and layouts
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import type { LayoutResult, Rectangle } from '../layout/pack';
import type { LayoutSettings } from '../layout/settings';

export interface SVGExportOptions {
  includeLabels: boolean;
  includeNotches: boolean;
  includeGrainlines: boolean;
  includeSeamAllowance: boolean;
  strokeWidth: number;
  fontSize: number;
}

export function createDefaultSVGOptions(): SVGExportOptions {
  return {
    includeLabels: true,
    includeNotches: true,
    includeGrainlines: true,
    includeSeamAllowance: true,
    strokeWidth: 1,
    fontSize: 12,
  };
}

export function exportLayoutToSVG(layout: LayoutResult, options: SVGExportOptions = createDefaultSVGOptions()): string {
  const { settings } = layout;
  const { paperSize } = settings;
  
  let svgContent = '';
  
  // Generate SVG for each page
  for (let i = 0; i < layout.pages.length; i++) {
    const page = layout.pages[i];
    const pagesvg = exportPageToSVG(page, settings, options);
    svgContent += pagesvg;
    
    if (i < layout.pages.length - 1) {
      svgContent += '\n\n<!-- Next Page -->\n\n';
    }
  }
  
  // Wrap in SVG document if single page, or return concatenated for multiple pages
  if (layout.pages.length === 1) {
    return createSVGDocument(paperSize.width, paperSize.height, svgContent, settings);
  } else {
    return svgContent;
  }
}

export function exportPageToSVG(
  page: { pieces: Rectangle[] }, 
  settings: LayoutSettings, 
  options: SVGExportOptions
): string {
  const { paperSize } = settings;
  
  let content = '';
  
  // Add pieces
  for (const piece of page.pieces) {
    content += exportPieceToSVG(piece, options);
  }
  
  // Add test square if enabled
  if (settings.showTestSquare) {
    content += createTestSquare();
  }
  
  return createSVGDocument(paperSize.width, paperSize.height, content, settings);
}

export function exportPieceToSVG(piece: Rectangle, options: SVGExportOptions): string {
  let content = '';
  
  // Main piece outline
  content += `<rect x="${piece.x}" y="${piece.y}" width="${piece.width}" height="${piece.height}" `;
  content += `fill="none" stroke="black" stroke-width="${options.strokeWidth}"/>\n`;
  
  // Add piece label if enabled
  if (options.includeLabels) {
    const centerX = piece.x + piece.width / 2;
    const centerY = piece.y + piece.height / 2;
    
    content += `<text x="${centerX}" y="${centerY}" `;
    content += `text-anchor="middle" dominant-baseline="middle" `;
    content += `font-family="Arial, sans-serif" font-size="${options.fontSize}">${piece.id}</text>\n`;
  }
  
  // Add grainline if enabled
  if (options.includeGrainlines) {
    const grainX1 = piece.x + piece.width * 0.2;
    const grainX2 = piece.x + piece.width * 0.8;
    const grainY = piece.y + piece.height * 0.9;
    
    content += `<line x1="${grainX1}" y1="${grainY}" x2="${grainX2}" y2="${grainY}" `;
    content += `stroke="black" stroke-width="${options.strokeWidth * 0.5}"/>\n`;
    
    // Arrow heads
    const arrowSize = 3;
    content += `<polygon points="${grainX1},${grainY} ${grainX1 + arrowSize},${grainY - arrowSize/2} ${grainX1 + arrowSize},${grainY + arrowSize/2}" `;
    content += `fill="black"/>\n`;
    content += `<polygon points="${grainX2},${grainY} ${grainX2 - arrowSize},${grainY - arrowSize/2} ${grainX2 - arrowSize},${grainY + arrowSize/2}" `;
    content += `fill="black"/>\n`;
  }
  
  // Add notches if enabled
  if (options.includeNotches) {
    // Add a sample notch at the top center
    const notchX = piece.x + piece.width / 2;
    const notchY = piece.y;
    const notchSize = 5;
    
    content += `<polygon points="${notchX},${notchY} ${notchX - notchSize/2},${notchY - notchSize} ${notchX + notchSize/2},${notchY - notchSize}" `;
    content += `fill="none" stroke="black" stroke-width="${options.strokeWidth * 0.5}"/>\n`;
  }
  
  return content;
}

function createTestSquare(): string {
  // 100mm test square in top-left corner
  return `<g id="test-square">
    <rect x="10" y="10" width="100" height="100" 
          fill="none" stroke="red" stroke-width="0.5" stroke-dasharray="2,2"/>
    <text x="60" y="65" text-anchor="middle" font-family="Arial, sans-serif" font-size="8" fill="red">
      100mm
    </text>
  </g>\n`;
}

function createSVGDocument(width: number, height: number, content: string, settings: LayoutSettings): string {
  const viewBox = `0 0 ${width} ${height}`;
  
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}mm" height="${height}mm" viewBox="${viewBox}" 
     xmlns="http://www.w3.org/2000/svg">
  <title>Pattern Layout - ${settings.paperFormat}</title>
  <desc>Generated by Seamly2D Web App - Scale: ${settings.scale}%</desc>
  
  <!-- Background -->
  <rect width="100%" height="100%" fill="white"/>
  
  <!-- Margins guide (optional) -->
  <rect x="${settings.margins.left}" y="${settings.margins.top}" 
        width="${width - settings.margins.left - settings.margins.right}" 
        height="${height - settings.margins.top - settings.margins.bottom}" 
        fill="none" stroke="#ccc" stroke-width="0.25" stroke-dasharray="1,1"/>
  
  <!-- Content -->
  ${content}
  
  <!-- Footer -->
  <text x="${width - 10}" y="${height - 5}" 
        text-anchor="end" font-family="Arial, sans-serif" font-size="6" fill="#666">
    Seamly2D Web App
  </text>
</svg>`;
}

/**
 * Download SVG content as file
 */
export function downloadSVG(content: string, filename: string = 'pattern-layout.svg'): void {
  const blob = new Blob([content], { type: 'image/svg+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}